name: Release

on:
  push:
    tags:
      - "*"
      - "!nightly-*"

concurrency:
  group: ${{ github.workflow_sha }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  resolve-commits:
    uses: ./.github/workflows/_resolve_openxla_commits.yaml
    with:
      source: pinned

  pjrt-artifacts:
    needs: resolve-commits
    uses: ./.github/workflows/_build.yaml
    with:
      xla_commit: ${{ needs.resolve-commits.outputs.xla_commit }}
      rocm_xla_commit: ${{ needs.resolve-commits.outputs.rocm_xla_commit }}
    secrets:
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

  release:
    name: "Release PJRT Artifacts"
    needs: ["pjrt-artifacts"]
    runs-on: ubuntu-latest
    steps:
      - run: rm -rf pjrt*.tar.gz
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz/*.tar.gz
